# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/bd/peripherals_inst_0/ip/peripherals_inst_0_axi_iic_0_0/peripherals_inst_0_axi_iic_0_0.xci
# IP: The module: 'peripherals_inst_0_axi_iic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/bd/peripherals_inst_0/ip/peripherals_inst_0_axi_iic_0_0/peripherals_inst_0_axi_iic_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'peripherals_inst_0_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/bd/peripherals_inst_0/ip/peripherals_inst_0_axi_iic_0_0/peripherals_inst_0_axi_iic_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'peripherals_inst_0_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/bd/peripherals_inst_0/ip/peripherals_inst_0_axi_iic_0_0/peripherals_inst_0_axi_iic_0_0.xci
# IP: The module: 'peripherals_inst_0_axi_iic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/bd/peripherals_inst_0/ip/peripherals_inst_0_axi_iic_0_0/peripherals_inst_0_axi_iic_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'peripherals_inst_0_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/bd/peripherals_inst_0/ip/peripherals_inst_0_axi_iic_0_0/peripherals_inst_0_axi_iic_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'peripherals_inst_0_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
