# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/BDC_top_bottom_ref_files/top.xdc

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_clk_wiz_1_0/top_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_clk_wiz_1_0 || ORIG_REF_NAME==top_clk_wiz_1_0} -quiet] -quiet

# IP: bd/top/ip/top_rst_clk_wiz_1_100M_0/top_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==top_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/top/ip/top_rst_ddr4_0_300M_0/top_rst_ddr4_0_300M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_rst_ddr4_0_300M_0 || ORIG_REF_NAME==top_rst_ddr4_0_300M_0} -quiet] -quiet

# IP: bd/top/ip/top_xbar_0/top_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xbar_0 || ORIG_REF_NAME==top_xbar_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_interconnect_0_0/top_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_interconnect_0_0 || ORIG_REF_NAME==top_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_bram_ctrl_0_0/top_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_bram_ctrl_0_0 || ORIG_REF_NAME==top_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_smc_0/top_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_smc_0 || ORIG_REF_NAME==top_axi_smc_0} -quiet] -quiet

# IP: bd/top/ip/top_ddr4_0_0/top_ddr4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ddr4_0_0 || ORIG_REF_NAME==top_ddr4_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_bram_ctrl_0_bram_0/top_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==top_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconstant_0_0/top_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconstant_0_0 || ORIG_REF_NAME==top_xlconstant_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_intc_0_0/top_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_intc_0_0 || ORIG_REF_NAME==top_axi_intc_0_0} -quiet] -quiet

# IP: bd/top/ip/top_mdm_1_0/top_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_mdm_1_0 || ORIG_REF_NAME==top_mdm_1_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconstant_1_0/top_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconstant_1_0 || ORIG_REF_NAME==top_xlconstant_1_0} -quiet] -quiet

# IP: bd/top/ip/top_microblaze_0_0/top_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_microblaze_0_0 || ORIG_REF_NAME==top_microblaze_0_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconcat_0_0/top_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconcat_0_0 || ORIG_REF_NAME==top_xlconcat_0_0} -quiet] -quiet

# IP: bd/top/ip/top_dlmb_v10_0/top_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dlmb_v10_0 || ORIG_REF_NAME==top_dlmb_v10_0} -quiet] -quiet

# IP: bd/top/ip/top_ilmb_v10_0/top_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ilmb_v10_0 || ORIG_REF_NAME==top_ilmb_v10_0} -quiet] -quiet

# IP: bd/top/ip/top_dlmb_bram_if_cntlr_0/top_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==top_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/top/ip/top_ilmb_bram_if_cntlr_0/top_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==top_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/top/ip/top_lmb_bram_0/top_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_lmb_bram_0 || ORIG_REF_NAME==top_lmb_bram_0} -quiet] -quiet

# XDC: /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/top_ooc.xdc
