# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.runs/synth_1/top_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcku040-ffva1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.cache/wt [current_project]
set_property parent.project_path /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kcu105:part0:1.7 [current_project]
set_property ip_output_repo /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files -quiet /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.runs/peripherals_inst_0_synth_1/peripherals_inst_0.dcp
set_property used_in_implementation false [get_files /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.runs/peripherals_inst_0_synth_1/peripherals_inst_0.dcp]
read_xdc hd_reconfig.xdc
set_property used_in_implementation false [get_files hd_reconfig.xdc]
read_verilog -library xil_defaultlib /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/hdl/top_wrapper.v
add_files /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.srcs/sources_1/bd/top/top.bd
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_clk_wiz_1_0/top_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_clk_wiz_1_0/top_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_clk_wiz_1_0/top_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_rst_clk_wiz_1_100M_0/top_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_rst_clk_wiz_1_100M_0/top_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_rst_clk_wiz_1_100M_0/top_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_rst_ddr4_0_300M_0/top_rst_ddr4_0_300M_0_board.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_rst_ddr4_0_300M_0/top_rst_ddr4_0_300M_0.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_rst_ddr4_0_300M_0/top_rst_ddr4_0_300M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_xbar_0/top_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_bram_ctrl_0_0/top_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_1/bd_b43a_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_1/bd_b43a_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_2/bd_b43a_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_2/bd_b43a_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_3/bd_b43a_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_3/bd_b43a_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_4/bd_b43a_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_5/bd_b43a_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_6/bd_b43a_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_7/bd_b43a_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_8/bd_b43a_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_12/bd_b43a_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_13/bd_b43a_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_14/bd_b43a_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_15/bd_b43a_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_16/bd_b43a_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_17/bd_b43a_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_21/bd_b43a_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_22/bd_b43a_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_23/bd_b43a_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_24/bd_b43a_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_25/bd_b43a_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_26/bd_b43a_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_27/bd_b43a_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_28/bd_b43a_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_29/bd_b43a_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_31/bd_b43a_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_32/bd_b43a_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_33/bd_b43a_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_34/bd_b43a_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_35/bd_b43a_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_36/bd_b43a_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_ddr4_0_0/bd_0/ip/ip_0/bd_1e58_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_ddr4_0_0/bd_0/ip/ip_0/bd_1e58_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_ddr4_0_0/bd_0/ip/ip_1/bd_1e58_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_ddr4_0_0/bd_0/ip/ip_1/bd_1e58_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_ddr4_0_0/bd_0/ip/ip_2/bd_1e58_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_ddr4_0_0/bd_0/ip/ip_3/bd_1e58_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_ddr4_0_0/bd_0/ip/ip_6/bd_1e58_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_ddr4_0_0/bd_0/ip/ip_9/bd_1e58_second_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_ddr4_0_0/bd_0/ip/ip_10/bd_1e58_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_ddr4_0_0/bd_0/bd_1e58_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_ddr4_0_0/ip_0/top_ddr4_0_0_microblaze_mcs_board.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_ddr4_0_0/ip_0/top_ddr4_0_0_microblaze_mcs_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_ddr4_0_0/ip_1/par/top_ddr4_0_0_phy_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_ddr4_0_0/top_ddr4_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_ddr4_0_0/par/top_ddr4_0_0.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_bram_ctrl_0_bram_0/top_axi_bram_ctrl_0_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_intc_0_0/top_axi_intc_0_0.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_intc_0_0/top_axi_intc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_axi_intc_0_0/top_axi_intc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_mdm_1_0/top_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_mdm_1_0/top_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_microblaze_0_0/top_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_microblaze_0_0/top_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_microblaze_0_0/top_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_dlmb_v10_0/top_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_ilmb_v10_0/top_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_dlmb_bram_if_cntlr_0/top_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_ilmb_bram_if_cntlr_0/top_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_lmb_bram_0/top_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/top_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_ddr4_0_0/bd_0/ip/ip_0/data/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_ddr4_0_0/ip_0/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_ddr4_0_0/sw/calibration_0/Debug/calibration_ddr.elf]
set_property used_in_implementation false [get_files -all /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/Lab_2.gen/sources_1/bd/top/ip/top_microblaze_0_0/data/mb_bootloop_le.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/BDC_top_bottom_ref_files/top.xdc
set_property used_in_implementation false [get_files /opt/Vivado-Design-Tutorials/Design_Flow_Tutorials/IP_Integrator/Lab_2/BDC_top_bottom_ref_files/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top_wrapper -part xcku040-ffva1156-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_wrapper_utilization_synth.rpt -pb top_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
